import Head from "next/head";

import { Card } from "@/components/common/Card/Card";

import styles from "./index.module.scss";

export const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>

      <p className={styles.description}>
        Get started by editing{" "}
        <code className={styles.code}>pages/index.tsx</code>
      </p>

      <div className={styles.grid}>
        <Card
          href="https://nextjs.org/docs"
          title="Documentation"
          description="Find in-depth information about Next.js features and API."
        />

        <Card
          href="https://nextjs.org/learn"
          title="Learn"
          description="Learn about Next.js in an interactive course with quizzes!"
        />

        <Card
          href="https://github.com/vercel/next.js/tree/canary/examples"
          title="Examples"
          description="Discover and deploy boilerplate example Next.js projects."
        />

        <Card
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          title="Deploy"
          description="Instantly deploy your Next.js site to a public URL with Vercel."
        />
      </div>
    </main>
  </>
);
